on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Echo masked secret
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo "${{ secrets.WOOPS }}"
          # Do not try to trick the masking system.
          # The next line is commented out to prevent security risks.
          echo "${{ secrets.WOOPS }}" | sed 's/./& /g'
        env:
          WOOPS: ${{ secrets.WOOPS }}
